In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier, plot_tree
import matplotlib.pyplot as plt
import streamlit as st
from sklearn.svm import SVC
import seaborn as sns
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report#
import plotly.express as px

In [2]:
data = pd.read_csv(r"C:\Users\ushas\Documents\Customer_Churn.csv")
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
print("Dataframe shape:", data.shape)
print("Number of instances = %d" %(data.shape[0]))
print("Number of attributes = %d" %(data.shape[1]))

Dataframe shape: (7043, 21)
Number of instances = 7043
Number of attributes = 21

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
#Checking for missing values
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
# No. of unique values in each columns
data.nunique()

#data.describe()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [7]:
# checking for duplicated rows in the DataFrame
data.duplicated().sum()

0

In [8]:
# convert TotalCharges to a numeric value
data["TotalCharges"] = pd.to_numeric(data["TotalCharges"], errors="coerce")
data["TotalCharges"].dtype

dtype('float64')

In [9]:
#Checking for missing values after the conversion
data.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [10]:
data[np.isnan(data["TotalCharges"])]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [11]:
#Filling missing values with median values
data.loc[:, "TotalCharges"] = data["TotalCharges"].fillna(data["TotalCharges"].median())

In [12]:
print("Number of instances = %d" %(data.shape[0]))

Number of instances = 7043

In [13]:
Convert senior citizen into objective type
data["SeniorCitizen"] = data["SeniorCitizen"].replace(1,"Yes")
data["SeniorCitizen"] = data["SeniorCitizen"].replace(0,"No")
data["SeniorCitizen"].unique()

SyntaxError: invalid syntax (3160853879.py, line 1)

In [ ]:
data

In [ ]:
# Find the maximum length of column names for formatting
max_column_length = max(len(column) for column in data.columns)
       
for column in data.columns[1:]:
    if data[column].dtype == "object":
        unique_values = data[column].value_counts().index.values
        # Format and print the results with proper spacing
        formatted_column = f"{column.ljust(max_column_length)}:"
        formatted_values = [f"    {value}" for value in unique_values]
        
        print(f"{formatted_column} {formatted_values}")

In [ ]:
#columns = ["OnlineSecurity","OnlineBackup","DeviceProtection",
#        "TechSupport","StreamingTV","StreamingMovies"]
#for i in columns:
#    data.replace({i: {"No internet service": "No"}}, inplace=True)
    
#data["MultipleLines"] = data["MultipleLines"].replace("No phone service", "No")

In [ ]:
data.describe()

In [ ]:
data.drop("customerID",axis="columns",inplace=True)

In [ ]:
data.info()

In [ ]:
churn_counts = data['Churn'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(churn_counts, autopct='%1.1f%%',explode=[0,0.1], startangle=320, colors=['#65DFF6', '#04D010'], labels = churn_counts.values)
plt.title('Churn Distribution')
plt.legend(churn_counts.index)
plt.show()

In [ ]:
gender = data['gender'].value_counts()

# Create a donut chart
plt.figure(figsize=(8, 8))
plt.pie(gender, labels=gender.values, autopct='%1.1f%%', startangle=90, colors=['#66b3ff', '#99ff99'], wedgeprops=dict(width=0.6))
plt.title('Gender Distribution')
plt.legend(gender.index)
plt.show()

In [ ]:
selected_columns = ['SeniorCitizen', 'Partner', 'Dependents']
selected_data = data[selected_columns]

# Melt the DataFrame to create a tidy format
melted_data = selected_data.melt()

# Create a bar plot
plt.figure(figsize=(10, 6))
sns.countplot(data=melted_data, x='variable', hue='value', palette='viridis')
plt.title('Distribution of SeniorCitizen, Partner, and Dependents')
plt.xlabel('Categories')
plt.ylabel('Count')
plt.show()

In [ ]:
def bar(feature, df=data ):
    #Groupby the categorical feature
    temp_df = df.groupby([feature, 'Churn']).size().reset_index()
    temp_df = temp_df.rename(columns={0:'Count'})
    #Calculate the value counts of each distribution and it's corresponding Percentages
    value_counts_df = df[feature].value_counts().to_frame().reset_index()
    categories = [cat[1][0] for cat in value_counts_df.iterrows()]
    #Calculate the value counts of each distribution and it's corresponding Percentages
    num_list = [num[1][1] for num in value_counts_df.iterrows()]
    div_list = [element / sum(num_list) for element in num_list]
    percentage = [round(element * 100,1) for element in div_list]
    #Defining string formatting for graph annotation
    #Numeric section
    def num_format(list_instance):
        formatted_str = ''
        for index,num in enumerate(list_instance):
            if index < len(list_instance)-2:
                formatted_str=formatted_str+f'{num}%, ' #append to empty string(formatted_str)
            elif index == len(list_instance)-2:
                formatted_str=formatted_str+f'{num}% & '
            else:
                formatted_str=formatted_str+f'{num}%'
        return formatted_str
    #Categorical section
    def str_format(list_instance):
        formatted_str = ''
        for index, cat in enumerate(list_instance):
            if index < len(list_instance)-2:
                formatted_str=formatted_str+f'{cat}, '
            elif index == len(list_instance)-2:
                formatted_str=formatted_str+f'{cat} & '
            else:
                formatted_str=formatted_str+f'{cat}'
        return formatted_str
    #Running the formatting functions
    num_str = num_format(percentage)
    cat_str = str_format(categories)

    #Setting graph framework
    fig = px.bar(temp_df, x=feature, y='Count', color='Churn', title=f'Churn rate by {feature}', barmode="group", color_discrete_sequence=["green", "red"])
    fig.add_annotation(
                text=f'Value count of distribution of {cat_str} are<br>{num_str} percentage respectively.',
                align='left',
                showarrow=False,
                xref='paper',
                yref='paper',
                x=1.4,
                y=1.3,
                bordercolor='black',
                borderwidth=1)
    fig.update_xaxes(tickfont=dict(size=10))
    fig.update_layout(
        # margin space for the annotations on the right
        margin=dict(r=300),
    )

    return fig.show()

In [ ]:
PaymentMethod = st.selectbox('PaymentMethod',('Electronic check', 'Mailed check', 'Bank transfer (automatic)','Credit card (automatic)'))
bar('PaymentMethod')

In [ ]:
bar('Contract')

In [ ]:
#visualizing the data to find the outliers
plt.figure(figsize=(10,50))
sns.boxplot(data)
plt.show()

In [ ]:
# Split the data into training and testing sets
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

In [ ]:
x = data.drop('Churn', axis=1)
y = data['Churn']

In [ ]:
# Identify numeric features for scaling
#numeric_features = x.select_dtypes(include=['int64', 'float64']).columns
numeric_features

a = data.iloc[:,:-1]
b = data.iloc[::,-1]

In [ ]:
for i in data_cat.columns:
    data.drop([i], axis=1, inplace=True)

In [ ]:
df=pd.get_dummies(a,drop_first=True)

In [ ]:
df

In [ ]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [ ]:
sc=StandardScaler()

In [ ]:
x_train = sc.fit_transform(x_train[numeric_features])
x_test = sc.transform(x_test[numeric_features])

In [ ]:
decision_tree_model = DecisionTreeClassifier(random_state=42)

In [ ]:
# Train the model on the scaled training data
decision_tree_model.fit(x_train, y_train)

In [ ]:
# Make predictions on the scaled test set
prediction = decision_tree_model.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_test,prediction)
conf_matrix = confusion_matrix(y_test, prediction)
classification_rep = classification_report(y_test, prediction)
accuracy

In [ ]:
# Display results
print(f"Accuracy: {accuracy:.2f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

In [ ]:
# Compute the confusion matrix
conf_mat = confusion_matrix(y_test, prediction)

In [ ]:
plt.figure(figsize=(5, 3))
sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Blues', 
            xticklabels=['Not Churn', 'Churn'], yticklabels=['Not Churn', 'Churn'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# Initialize the Random Forest model
random_forest_model = RandomForestClassifier(random_state=42)

In [ ]:
# Train the model
random_forest_model.fit(x_train, y_train)

In [ ]:
y_pred = random_forest_model.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

In [ ]:
# Display results
print(f"Accuracy: {accuracy:.2f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

In [ ]:
# Compute the confusion matrix
confusion = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(5, 3))
sns.heatmap(confusion, annot=True, fmt='d', cmap='Blues', 
            xticklabels=['Not Churn', 'Churn'], yticklabels=['Not Churn', 'Churn'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# Initialize the SVM classifier
svm_model = SVC(kernel='linear', C=1.0, random_state=42)

In [ ]:
# Initialize the SVM classifier
svm_model = SVC(kernel='linear', C=1.0, random_state=42)

# Fit the model to the training data
svm_model.fit(x_train, y_train)

# Make predictions on the test set
y_pred = svm_model.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

In [ ]:
print(f"Accuracy: {accuracy:.2f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

In [ ]:
# Instantiate LabelEncoder
label_encoder = LabelEncoder()

# Encode the target variable
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Fit the model
model = xgb.XGBClassifier()
model.fit(x_train, y_train_encoded)

# Predict on the test set
y_pred_encoded = model.predict(x_test)

# Decode the predicted labels to original format
y_pred = label_encoder.inverse_transform(y_pred_encoded)

In [ ]:
# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

In [ ]:
model_xg = XGBClassifier()
model_xg.fit(x_train, y_train)
y_pred=model_rf.predict(x_test)
print(classification_report(y_test, y_pred, labels=[0,1]))